name: auto_opt_varifacation
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  sizer: ^2.0.13
  sms_autofill: ^2.1.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter



